Apply backend validation for User First and last name
Crown-Commercial-Service/conclave-ssso pull request #603
Opened 2022-05-18 14:34 UTC by karpagamNallasamy

Note : API response alert have confirmed with Artur

2022-05-18 16:01 UTC, VijayHirudayasamy-bc requested changes

2022-05-18 16:01 UTC, VijayHirudayasamy-bc commented on api/CcsSso.Shared/Domain/Helpers/UtilityHelper.cs
> +      if (string.IsNullOrWhiteSpace(Name))
Can we add required field attributes to the model to avoid this check

2022-05-19 07:05 UTC, karpagamNallasamy commented
Resolved as per comments. Committed and pushed into this same PR.

Please take on look.

________________________________
From: VijayHirudayasamy-bc ***@***.***>
Sent: Wednesday, May 18, 2022 9:32:06 PM
To: Crown-Commercial-Service/conclave-ssso ***@***.***>
Cc: Karpagam Nallasamy ***@***.***>; Author ***@***.***>
Subject: Re: [Crown-Commercial-Service/conclave-ssso] Apply backend validation for User First and last name (PR #603)


@VijayHirudayasamy-bc requested changes on this pull request.

________________________________

In api/CcsSso.Shared/Domain/Constants/RegexExpression.cs<https://github.com/Crown-Commercial-Service/conclave-ssso/pull/603#discussion_r876055559>:

> @@ -6,5 +6,6 @@ public static class RegexExpression
     public const string VALID_EMAIL_FORMAT_REGEX = @"^\s?([\w\.+! -\/]*)@([\w\.\-]+)((\.(\w){1,1000})+)\s?$";
     public const string VALID_PHONE_E164_FORMAT_REGEX = @"^\+[1-9]\d{1,14}$";
     public const string VALID_PASSWORD_FORMAT_REGEX = @"^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[!@#$%^&*_]).{4,}$";
+    public const string VALID_USER_NAME = @"[a-zA-Z-,'.-]+$";


Please explain what are required, It allows A-Z,a-z and four special characters.(, . - '). Is any other special char required.

________________________________

In api/CcsSso.Shared/Domain/Helpers/UtilityHelper.cs<https://github.com/Crown-Commercial-Service/conclave-ssso/pull/603#discussion_r876077971>:

> @@ -71,5 +71,35 @@ public static bool IsPasswordValidForRequiredCharactors(string password)
       Match match = regex.Match(password);
       return match.Success;
     }
+
+    public static bool IsUserNameValid(string Name)
+    {
+      if (string.IsNullOrWhiteSpace(Name))


Can we add required field attributes to the model to avoid this check

—
Reply to this email directly, view it on GitHub<https://github.com/Crown-Commercial-Service/conclave-ssso/pull/603#pullrequestreview-977195044>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXH6RBPYUDPQJ36YMBD35QDVKUH75ANCNFSM5WIWKPWA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

------------------------------------------------------------------------------------------------------------ This transmission has been sent by either Brickendon Consulting Limited, Brickendon Consulting (US) Inc. or Brickendon Consulting (Poland) Sp. z o.o., referred to below as “Brickendon”. This email and any attachments relating to the official business of Brickendon is proprietary to Brickendon, confidential and may be privileged. This message is intended solely for the addressee(s) of this email who are the sole authorised recipient(s). If you have received this message in error, please send it back to us, and immediately and permanently delete it. Do not use, copy, or disclose the information contained in this message or in any attachment or base any action on it. Brickendon cannot ensure that the integrity of this email has been maintained nor that it is free of errors, virus, interception or interference. The sender therefore does not accept liability for any errors or omissions in the contents of this message which arise as a result of e-mail transmission. You should check that any attachments are virus free before opening them. Any views or statements in attachments are (unless the context or letter sign off otherwise makes it clear) solely those of the author and do not necessarily represent those of Brickendon. Brickendon Consulting Limited is registered in England with company number 07262520 and whose registered office is at 4 Prince Albert Road, London, NW1 7SN. Brickendon Consulting (US) Inc. is registered in the United States of America with company number 6022535 and whose registered office is at 3500 South Dupont Highway, Dover DE 19901. Brickendon Consulting (Poland) Sp. z o.o. is registered in Poland with company number KRS000070318 and whose registered office is at Ulica Przemyslawa Gintrowskiego 31, 02-697 Warzawa. More information on Brickendon is available at www.brickendon.com -----------------------------------------------------------------------------------------------------------------------------

2022-05-19 09:10 UTC, VijayHirudayasamy-bc requested changes

2022-05-19 09:10 UTC, VijayHirudayasamy-bc commented on api/CcsSso.Shared/Domain/Helpers/UtilityHelper.cs
> +      try
please fix the formatting

2022-05-19 09:10 UTC, VijayHirudayasamy-bc commented on api/CcsSso.Shared/Domain/Helpers/UtilityHelper.cs
> +      if (Name.Length <= 1)
Can we simplify this methods as follows 
return Name.Length <= 1 ? false : true;
Please check and let me know your thought. Please test it

2022-05-19 10:37 UTC, VijayHirudayasamy-bc approved these changes
Approved. Please follow up to deliver the PR.
Hope the QA Buddy check has been done

2022-05-23 10:24 UTC, VijayHirudayasamy-bc approved these changes

2022-05-23 10:26 UTC, merged